import { FurnitureCategory, StairType } from './types';

export interface LibraryItem {
  id: string;
  name: string;
  nameUrdu: string;
  category: FurnitureCategory | 'structural' | 'stairs' | 'door_preset' | 'window_preset' | 'plot_preset';
  stairType?: StairType;
  width: number; // inches
  height: number; // inches
  fillColor?: string;
  strokeColor?: string;
  defaultLabel?: string;
  marla?: number;
}

export const LIBRARY_ITEMS: LibraryItem[] = [
  // Bedroom
  {
    id: 'bed-king',
    name: 'King Bed (6ft × 6.5ft)',
    nameUrdu: 'Bara Palang (King Bed)',
    category: 'bed',
    width: 72,
    height: 78,
    defaultLabel: 'King Bed',
    fillColor: 'rgba(56, 189, 248, 0.08)',
    strokeColor: '#38bdf8',
  },
  {
    id: 'bed-single',
    name: 'Single Bed (3ft × 6.5ft)',
    nameUrdu: 'Chhota Palang (Single Bed)',
    category: 'bed',
    width: 36,
    height: 78,
    defaultLabel: 'Single Bed',
    fillColor: 'rgba(56, 189, 248, 0.08)',
    strokeColor: '#38bdf8',
  },

  // Living Room / Sofas
  {
    id: 'sofa-3seat',
    name: '3-Seater Sofa (7ft × 3ft)',
    nameUrdu: '3-Nashist Sofa',
    category: 'sofa',
    width: 84,
    height: 36,
    defaultLabel: '3-Seat Sofa',
    fillColor: 'rgba(245, 158, 11, 0.08)',
    strokeColor: '#f59e0b',
  },
  {
    id: 'sofa-2seat',
    name: '2-Seater Sofa (5ft × 3ft)',
    nameUrdu: '2-Nashist Sofa',
    category: 'sofa',
    width: 60,
    height: 36,
    defaultLabel: '2-Seat Sofa',
    fillColor: 'rgba(245, 158, 11, 0.08)',
    strokeColor: '#f59e0b',
  },
  {
    id: 'sofa-armchair',
    name: 'Armchair (3ft × 3ft)',
    nameUrdu: 'Aramdeh Kursi (Armchair)',
    category: 'sofa',
    width: 36,
    height: 36,
    defaultLabel: 'Armchair',
    fillColor: 'rgba(245, 158, 11, 0.08)',
    strokeColor: '#f59e0b',
  },

  // Dining & Tables
  {
    id: 'table-dining-6',
    name: 'Dining Table 6-Seat (5ft × 3ft)',
    nameUrdu: 'Khaane Ka Mez (6 Person)',
    category: 'table',
    width: 60,
    height: 36,
    defaultLabel: 'Dining Table',
    fillColor: 'rgba(168, 85, 247, 0.08)',
    strokeColor: '#a855f7',
  },
  {
    id: 'table-coffee',
    name: 'Coffee Table (3ft × 2ft)',
    nameUrdu: 'Chaye Ka Mez (Coffee Table)',
    category: 'table',
    width: 36,
    height: 24,
    defaultLabel: 'Coffee Table',
    fillColor: 'rgba(168, 85, 247, 0.08)',
    strokeColor: '#a855f7',
  },
  {
    id: 'table-desk',
    name: 'Office / Study Desk (4ft × 2ft)',
    nameUrdu: 'Parhai Ka Mez (Study Desk)',
    category: 'table',
    width: 48,
    height: 24,
    defaultLabel: 'Study Desk',
    fillColor: 'rgba(168, 85, 247, 0.08)',
    strokeColor: '#a855f7',
  },

  // Kitchen
  {
    id: 'kitchen-counter',
    name: 'Kitchen Sink Counter (8ft × 2ft)',
    nameUrdu: 'Bawarchikhana Counter & Sink',
    category: 'counter',
    width: 96,
    height: 24,
    defaultLabel: 'Kitchen Counter',
    fillColor: 'rgba(16, 185, 129, 0.08)',
    strokeColor: '#10b981',
  },
  {
    id: 'kitchen-stove',
    name: 'Cooking Stove (3ft × 2ft)',
    nameUrdu: 'Chulha (Stove)',
    category: 'counter',
    width: 36,
    height: 24,
    defaultLabel: 'Stove Unit',
    fillColor: 'rgba(16, 185, 129, 0.08)',
    strokeColor: '#10b981',
  },

  // Bathroom
  {
    id: 'bath-wc',
    name: 'WC Commode (1.5ft × 2.3ft)',
    nameUrdu: 'Commode / WC',
    category: 'bath',
    width: 18,
    height: 28,
    defaultLabel: 'WC',
    fillColor: 'rgba(14, 165, 233, 0.08)',
    strokeColor: '#0ea5e9',
  },
  {
    id: 'bath-basin',
    name: 'Wash Basin (2ft × 1.5ft)',
    nameUrdu: 'Dast-shoo (Wash Basin)',
    category: 'bath',
    width: 24,
    height: 18,
    defaultLabel: 'Basin',
    fillColor: 'rgba(14, 165, 233, 0.08)',
    strokeColor: '#0ea5e9',
  },
  {
    id: 'bath-shower',
    name: 'Shower Enclosure (3ft × 3ft)',
    nameUrdu: 'Ghusalkhana Shower Cubicle',
    category: 'bath',
    width: 36,
    height: 36,
    defaultLabel: 'Shower',
    fillColor: 'rgba(14, 165, 233, 0.08)',
    strokeColor: '#0ea5e9',
  },

  // Structural & Stairs
  {
    id: 'struct-stairs-straight',
    name: 'Straight Stairs (3.5ft × 12ft)',
    nameUrdu: 'Seedhi Seedhiyan (Straight Stairs)',
    category: 'stairs',
    stairType: 'straight',
    width: 42,
    height: 144,
    defaultLabel: 'Straight Stairs (UP ↑)',
    fillColor: 'rgba(148, 163, 184, 0.1)',
    strokeColor: '#38bdf8',
  },
  {
    id: 'struct-stairs-l',
    name: 'L-Shape Stairs with Landing (6ft × 8ft)',
    nameUrdu: 'L-Shaped Seedhiyan (Landing Wali)',
    category: 'stairs',
    stairType: 'l_shape',
    width: 42,
    height: 96,
    defaultLabel: 'L-Shape Stairs (UP ↑)',
    fillColor: 'rgba(148, 163, 184, 0.1)',
    strokeColor: '#38bdf8',
  },
  {
    id: 'struct-stairs-u',
    name: 'U-Shape Dog-legged Stairs (7ft × 10ft)',
    nameUrdu: 'U-Shaped Dog-legged Seedhiyan',
    category: 'stairs',
    stairType: 'u_shape',
    width: 42,
    height: 120,
    defaultLabel: 'U-Shape Stairs (UP ↑)',
    fillColor: 'rgba(148, 163, 184, 0.1)',
    strokeColor: '#38bdf8',
  },
  {
    id: 'struct-stairs-spiral',
    name: 'Spiral Circular Stairs (6ft dia)',
    nameUrdu: 'Chakardaar / Gol Seedhiyan (Spiral)',
    category: 'stairs',
    stairType: 'spiral',
    width: 72,
    height: 72,
    defaultLabel: 'Spiral Stairs (UP ↑)',
    fillColor: 'rgba(148, 163, 184, 0.1)',
    strokeColor: '#38bdf8',
  },
  {
    id: 'struct-stairs-winder',
    name: 'Quarter-Turn Winder Stairs',
    nameUrdu: 'Winder Stairs (Mor Wali Seedhiyan)',
    category: 'stairs',
    stairType: 'winder',
    width: 42,
    height: 120,
    defaultLabel: 'Winder Stairs (UP ↑)',
    fillColor: 'rgba(148, 163, 184, 0.1)',
    strokeColor: '#38bdf8',
  },
  {
    id: 'struct-column-9',
    name: 'Square Column 9" × 9"',
    nameUrdu: 'Chaukor Column 9x9',
    category: 'column',
    width: 9,
    height: 9,
    defaultLabel: 'C1',
    fillColor: '#475569',
    strokeColor: '#38bdf8',
  },
  {
    id: 'struct-column-12',
    name: 'Square Column 12" × 12"',
    nameUrdu: 'Chaukor Column 12x12',
    category: 'column',
    width: 12,
    height: 12,
    defaultLabel: 'C2',
    fillColor: '#475569',
    strokeColor: '#38bdf8',
  },
  {
    id: 'struct-beam',
    name: 'Structural Beam (9" × 12ft)',
    nameUrdu: 'Chhat Ka Beam (Beam)',
    category: 'beam',
    width: 144,
    height: 9,
    defaultLabel: 'B1 (Beam)',
    fillColor: 'rgba(56, 189, 248, 0.1)',
    strokeColor: '#38bdf8',
  },

  // Plot Presets
  {
    id: 'plot-3marla',
    name: '3 Marla Plot (20ft × 41ft)',
    nameUrdu: '3 Marla Plot (20x41)',
    category: 'plot_preset',
    width: 240, // 20 ft
    height: 492, // 41 ft
    marla: 3,
    defaultLabel: '3 Marla Plot',
  },
  {
    id: 'plot-5marla',
    name: '5 Marla Plot (25ft × 54.5ft)',
    nameUrdu: '5 Marla Plot (25x54.5)',
    category: 'plot_preset',
    width: 300, // 25 ft
    height: 654, // 54.5 ft
    marla: 5,
    defaultLabel: '5 Marla Plot (25×54.5)',
  },
  {
    id: 'plot-7marla',
    name: '7 Marla Plot (30ft × 63.5ft)',
    nameUrdu: '7 Marla Plot (30x63.5)',
    category: 'plot_preset',
    width: 360,
    height: 762,
    marla: 7,
    defaultLabel: '7 Marla Plot',
  },
  {
    id: 'plot-10marla',
    name: '10 Marla Plot (35ft × 78ft)',
    nameUrdu: '10 Marla Plot (35x78)',
    category: 'plot_preset',
    width: 420,
    height: 934,
    marla: 10,
    defaultLabel: '10 Marla Plot',
  },
  {
    id: 'plot-1kanal',
    name: '1 Kanal Plot (50ft × 109ft)',
    nameUrdu: '1 Kanal Plot (50x109)',
    category: 'plot_preset',
    width: 600,
    height: 1307,
    marla: 20,
    defaultLabel: '1 Kanal Plot (50×109)',
  },
];
